### ISSUE TITLE
Error: Cannot find module 'yargs/yargs'

### ISSUE THREAD

**Issue by jkoop** [tkoop/speedsong#2]
```
jkoop@localhost:~/speedsong$ node speedsong --notes "E,D,C,D,E,E,E2,D,D,D2,E,G,G2,E,D,C,D,E,E,E,E,D,D,E,D,C4"
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yargs/yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/joek/Documents/Git/tkoop/speedsong/speedsong.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
jkoop@localhost:~/speedsong$ 
```

**Comment by tkoop** [comment]
Try running:

node install
